<?php

/**
 * (c) InPost UK Ltd <it_support@inpost.co.uk>
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 *
 * Built by NMedia Systems Ltd, <info@nmediasystems.com>
 */

?>
<?php  $_order = $this->getOrder() ?>
<p class="order-links">
    <a href="<?php echo $this->getPrintAllShipmentsUrl($_order) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print All Shipments') ?></a>
</p>
<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
    <h2 class="sub-title"><?php echo $this->__('Shipment #') ?><?php echo $_shipment->getIncrementId(); ?> <span class="separator">|</span> <a href="<?php echo $this->getPrintShipmentUrl($_shipment) ?>" onclick="this.target='_blank'" class="link-print"><?php echo $this->__('Print Shipment') ?></a></h2>
    <?php $tracks = $_shipment->getTracksCollection(); ?>
    <?php  if ($tracks->count()): ?>
        <table class="data-table tracking-table" id="my-tracking-table-<?php echo $_shipment->getId(); ?>">
            <tbody>
            <tr>
                <td colspan="2">
                    <?php if (strpos($_order->getShippingMethod(), 'inpost_lockers') !== false) :?>
                        <a target="_blank" href="https://tracking.inpost.co.uk/?parcel_number=<?php echo $tracks->getFirstItem()->getTrackNumber() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Track this shipment')) ?>"><?php echo $this->__('Track this shipment') ?></a>
                    <?php else: ?>
                        <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_shipment) ?>','trackshipment','width=800,height=600,top=0,left=0,resizable=yes,scrollbars=yes'); return false;" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Track this shipment')) ?>"><?php echo $this->__('Track this shipment') ?></a>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th class="label"><?php echo $this->__('Tracking Number(s):') ?></th>
                <td>&nbsp;
                    <?php
                    $i = 1;
                    $_size = $tracks->count();
                    foreach($tracks as $track): ?>
                    <?php if ($track->getCarrierCode() == 'inpost') :?>
                            <a href="https://tracking.inpost.co.uk/?parcel_number=<?php echo $track->getNumber()  ?>" target="_blank" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Track this shipment')) ?>"><?php echo $this->escapeHtml($track->getNumber()) ?></a>
                        <?php elseif($track->isCustom()): ?>
                            <?php echo $this->escapeHtml($track->getNumber()) ?>
                        <?php else: ?>
                            <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes')" ><?php echo $this->escapeHtml($track->getNumber()) ?></a>
                        <?php endif; ?>
                        <?php if($i!=$_size): ?>, <?php endif; ?>
                        <?php $i++;
                    endforeach; ?>
                </td>
            </tr>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('my-tracking-table-<?php echo $_shipment->getId(); ?>')</script>
    <?php  endif; ?>
    <h3 class="table-caption"><?php echo $this->__('Items Shipped') ?></h3>
    <table class="data-table" id="my-shipment-table-<?php echo $_shipment->getId(); ?>">
        <col />
        <col width="1" />
        <col width="1" />
        <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('SKU') ?></th>
            <th class="a-center"><span class="nobr"><?php echo $this->__('Qty Shipped') ?></span></th>
        </tr>
        </thead>
        <?php $_items = $_shipment->getAllItems(); ?>
        <?php $_count = count($_items) ?>
        <?php foreach ($_items as $_item): ?>
            <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
            <tbody>
            <?php echo $this->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
    <script type="text/javascript">decorateTable('my-shipment-table-<?php echo $_shipment->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
    <?php echo $this->getCommentsHtml($_shipment)?>
<?php endforeach; ?>
