<?php
/**
 * (c) InPost UK Ltd <it_support@inpost.co.uk>
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 *
 * Built by NMedia Systems Ltd, <info@nmediasystems.com>
 */
?>
<?php  $_order = $this->getShipment()->getOrder() ?>
<?php echo $this->getChildHtml('order_info') ?>
<?php $parcelData = (array)json_decode($this->getShipment()->getParcelData()); ?>
<?php $helper = Mage::helper('inpost_lockers') ?>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo $this->helper('sales')->__('Payment Information') ?></h4>
        </div>
        <fieldset>
            <div><?php echo $this->getChildHtml('order_payment') ?></div>
            <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-method"><?php echo $this->helper('sales')->__('Shipping and Tracking Information') ?></h4>
        </div>
        <fieldset>
            <div>
                <?php if($this->getShipment()->getTracksCollection()->count()): ?>
                    <?php if (strpos($_order->getShippingMethod(), 'inpost_lockers') !== false) :?>
                        <a href="https://tracking.inpost.co.uk/?parcel_number=<?php echo $parcelData['id'] ?>" target="_blank" id="linkId" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Track this shipment')) ?>"><?php echo $this->__('Track this shipment') ?></a>
                    <?php else: ?>
                        <a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($this->getShipment()) ?>','trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Track this shipment')) ?>"><?php echo $this->__('Track this shipment') ?></a>
                    <?php endif;?>
                    <br/>
                <?php endif; ?>
                <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>
                <?php echo $this->helper('sales')->__('Total Shipping Charges'); ?>:

                <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                    <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                <?php else: ?>
                    <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                <?php endif; ?>
                <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                <?php echo $_excl; ?>
                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>
            </div>
            <?php if (strpos($_order->getShippingMethod(), 'inpost_lockers') !== false && $helper->getCreateLabelsInMagentoFlag()) :?>
                <button title="Get shipping label" type="button" class="scalable " onclick="window.open('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'inpost/shipping-labels/' . $_order->getIncrementId() . '_' . $parcelData['id'] . '.' . $helper->getLabelsFormat()?>', '_blank')" style="">
                    <span>
                        <span>
                            <span>Print Shipping Label</span>
                        </span>
                    </span>
                </button>
            <?php else: ?>
                <?php if ($this->canCreateShippingLabel()): ?>
                    <div style="text-align: center; margin: 10px 0;">
                        <?php echo $this->getCreateLabelButton()?>
                        <?php if ($this->getShipment()->getShippingLabel()): ?>
                            <?php echo $this->getPrintLabelButton() ?>
                        <?php endif ?>
                        <?php if ($this->getShipment()->getPackages()): ?>
                            <?php echo $this->getShowPackagesButton() ?>
                        <?php endif ?>
                    </div>
                <?php endif ?>
            <?php endif;?>
            <div><?php echo $this->getChildHtml('shipment_tracking') ?></div>
        </fieldset>
        <?php echo $this->getChildHtml('shipment_packaging') ?>
        <script type="text/javascript">
            //<![CDATA[
            document.observe("dom:loaded", function() {
                setTimeout(function(){
                    packaging.setConfirmPackagingCallback(function(){
                        packaging.sendCreateLabelRequest();
                    });
                    packaging.setLabelCreatedCallback(function(response){
                        setLocation("<?php echo $this->getUrl(
                            '*/sales_order_shipment/view',
                            array('shipment_id' => $this->getShipment()->getId())
                        ); ?>");
                    });
                }, 500);
            });
            //]]>
        </script>
    </div>
</div>
<div class="clear"></div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-products"><?php echo $this->helper('sales')->__('Items Shipped') ?></h4>
    </div>
</div>

<?php echo $this->getChildHtml('shipment_items') ?>
<?php echo $this->getChildHtml('shipment_packed') ?>

<div class="box-left entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Shipment History') ?></h4></div>
    <fieldset><?php echo $this->getChildHtml('order_comments') ?></fieldset>
</div>
<div class="clear"></div>
